root = "@TERMUX_PREFIX@/lib/containerd"
state = "@TERMUX_PREFIX@/run/containerd"
imports = ["@TERMUX_PREFIX@/etc/containerd/runtime_*.toml", "./debug.toml"]

[grpc]
  address = "@TERMUX_PREFIX@/run/containerd/containerd.sock"

[debug]
  address = "@TERMUX_PREFIX@/run/containerd/debug.sock"
